INSERT INTO cliente (id_cliente,nome,email) VALUES (1,'Michel','michelzarpe@gmail.com')
INSERT INTO cliente (id_cliente,nome,email) VALUES (2,'Eduardo','eduardo@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (3,'Enrico','enrico@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (4,'Enzo','enzo@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (5,'Erick','erick@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (6,'Felipe','felipe@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (7,'Fernando','fernando@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (8,'Francisco','francisco@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (9,'Frederico','frederico@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (10,'Guilherme','guilherme@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (11,'Gustavo','gustavo@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (12,'Yuri','yuri@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (13,'Thomas','thomas@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (14,'Augusto','augusto@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (15,'Rian','rian@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (16,'Daniel','daniel@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (17,'Felipe','felipe@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (18,'Alexandre','alexandre@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (19,'Isaac','isaac@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (20,'Yago','yago@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (21,'Danilo','danilo@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (22,'Bruno','bruno@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (23,'Thiago','thiago@yahoo.com.br')
INSERT INTO cliente (id_cliente,nome,email) VALUES (24,'Otávio','otavio@yahoo.com.br')


