INSERT INTO PERGUNTA (ID_PERGUNTA,DESCRICAO) VALUES (1,'COMO FOI A VIAGEM');
INSERT INTO PERGUNTA (ID_PERGUNTA,DESCRICAO) VALUES (2,'PONTOS TURISTICOS');

INSERT INTO AVALIACAO (ID_AVALIACAO,ID_PACOTE_VIAGEM,STATUS) VALUES (1,1,'RESPONDIDO'); 
INSERT INTO AVALIACAO (ID_AVALIACAO,ID_PACOTE_VIAGEM,STATUS) VALUES (2,2,'CRIADO'); 



INSERT INTO ANEXO (ID_ANEXO,ID_CLIENTE,ID_AVALIACAO,ARQUIVO,TYPE) VALUES (1,1,1,'BASE64XXXX','FOTO');



INSERT INTO AVALIACAO_PERGUNTA (ID_AVALIACAO_PERGUNTA,ID_PERGUNTA,ID_AVALIACAO) VALUES (1,1,1);
INSERT INTO AVALIACAO_PERGUNTA (ID_AVALIACAO_PERGUNTA,ID_PERGUNTA,ID_AVALIACAO) VALUES (2,2,1);


INSERT INTO RESPOSTA (ID_RESPOSTA,ID_AVALIACAO_PERGUNTA,ID_CLIENTE,NOTA) VALUES (1,1,1,8);
INSERT INTO RESPOSTA (ID_RESPOSTA,ID_AVALIACAO_PERGUNTA,ID_CLIENTE,NOTA) VALUES (2,2,1,9);



